# Generated by Django 5.0.7 on 2024-08-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
